from pydantic import BaseModel, Field
from typing import Annotated, Literal
from operator import add

class AgentSchema(BaseModel):
    messages : Annotated[list,add] = Field(..., description="List Of Messages To Be Processed by the agent.")
    user_question : str = Field(..., description = "The original question asked by the user")
    curated_question : str = Field(..., description = "Curated User Question")
    prompt_query_context : str = Field(..., description="A Detailed Prompt With SQL DB Context That Wull Help Agent Generate SQL Quuery")
    is_safe : Literal["Yes","No"] = Field(..., description = "Indicate Weather the generated SQL Query is safe to execute or not")
    generated_sql_query : str = Field(..., description = "The SQL Query generated by the agent based on the curated question and prompt context")
    sql_query_execution_result : str = Field(..., description = "the result of executing the generated SQL query on the database")
    final_answer : str = Field(..., description="The Final answer generated by the agent based on SQL query execution result")
    
class JudgeSchema(BaseModel):
    answer : Literal['Yes','No'] = Field(description = "indicates weather the geneated SQL query is safe to execute or not")
    comments : str = Field(description = "Additional comments or feedback from the judge regarding the SQL query ")